import "./globals.css";

export const metadata = {
  title: "Gif Search",
  description: "Generated by Arjun Sarkar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
